### ISSUE TITLE
Message group for some instant, less formal discussions?

### ISSUE THREAD

**Issue by moulin1024** [bsaepfl/start-here#1]
Hi,

While I agree development-related discussion should primarily be done through github issues page so that it is traceable and well-documented, I think it might help to also create an IM group (telegram/Slack) so that some instant, less formal discussions (random thoughts, meet-up organization etc) could take place there?

Cheers,
Mou

**Comment by louismerlin** [comment]
Yes mabye you're right. I'll create a telegram group asap.
